
name: ejelacic_docker_compose

services:
   tvrtka_ejelacic:
     build:
       context: ./ejelacic_vjezba_08_dz_3_tvrtka
       dockerfile: Dockerfile
     container_name: tvrtka_ejelacic
     image: ejelacic/tvrtka:latest
     hostname: tvrtka_ejelacic
     volumes:
       - svezak_ejelacic:/usr/app/podaci
     networks:
       mreza_ejelacic:
         ipv4_address: 20.24.5.2
      


   partner_ejelacic:
     build:
       context: ./ejelacic_vjezba_08_dz_3_partner
       dockerfile: Dockerfile
     container_name: partner_ejelacic
     image: ejelacic/partner:latest 
     hostname: partner_ejelacic
     volumes:
       - svezak_ejelacic:/usr/app/podaci
     networks:
       mreza_ejelacic:
         ipv4_address: 20.24.5.3
     depends_on:
       - tvrtka_ejelacic
     ports: 
       - "5005:5005" 
    
 
   servisi:
     build:
       context: ./ejelacic_vjezba_08_dz_3_servisi
       dockerfile: Dockerfile
     container_name: servis_ejelacic
     image: ejelacic/servis:latest
     hostname: servis_ejelacic
     networks:
       mreza_ejelacic:
         ipv4_address: 20.24.5.20
  
   
volumes:
   svezak_ejelacic:
     external: true


networks:
   mreza_ejelacic:
     external: true
     driver: bridge
     ipam:
       config:
         - subnet: 20.24.5.0/24
   



